README.rdoc
Was eager to try v2 on master and saw the note [here](https://github.com/ambethia/recaptcha/issues/112#issuecomment-66671727).
=> config.api_version documentation

test/recaptcha_configuration_test.rb, test/recaptcha_test.rb, test/recaptcha_v1_test.rb
Adding some v2 tests.  They are very high level.  Please let me know if I need to go more in-depth.
=> Adding some unit tests for v2

lib/recaptcha/verify.rb
Some fixes to integrate with Grape API (https://github.com/intridea/grape)
=> Integrate with Grape

README.md
@olivierlacan  @ambethia @kintner 
reducing it to the recommended / simple setup and making everything else after, I hope this is easier to digest.
=> streamline readme

README.md
Due to the number of people having problems with expired stokens: https://github.com/ambethia/recaptcha/issues/137 this clarification in the README should help.
=> Clarify the role of the system clock in generating the stoken

README.md, lib/recaptcha/verify.rb, test/verify_test.rb
Refs https://github.com/ambethia/recaptcha/issues/167
=> Make possible to use custom domain name validation

lib/recaptcha/verify.rb, test/verify_test.rb
In reference to https://github.com/ambethia/recaptcha/issues/171. This is all that would be necessary without adding an option. Let me know if you want me to try it with some sort of config option, to support previous behavior
=> Skip flash error when model is present

README.md
More info:
- https://developers.google.com/recaptcha/docs/display#config
- https://developers.google.com/recaptcha/docs/language
=> Document the "hl" option for recaptcha_tags

README.md, lib/recaptcha/configuration.rb, lib/recaptcha/verify.rb, test/verify_test.rb
=> Add global hostname validator config

README.md, lib/recaptcha.rb, lib/recaptcha/client_helper.rb, lib/recaptcha/configuration.rb, test/client_helper_test.rb, test/configuration_test.rb, test/helper.rb
@ambethia @nate00  @astuyve @mcls  @JustMikey  @davingee @tomprats  thoughts ?
=> get rid of all unsecure things

README.md, lib/recaptcha/client_helper.rb, test/client_helper_test.rb
some times you need this two options
=> Add id tag attribute and script true/false options

lib/recaptcha/client_helper.rb
Recently, they released new reCAPTCHA. (currently beta)
https://developers.google.com/recaptcha/docs/invisible
=> Support invisible reCAPTCHA

lib/recaptcha/client_helper.rb, test/client_helper_test.rb
=> Allow random attributes to be rendered for invisible captcha button

lib/recaptcha/client_helper.rb, test/client_helper_test.rb
Fix missing data-sitekey attribute.
=> Add site key back to data attributes

lib/recaptcha/client_helper.rb, test/client_helper_test.rb
Add relevant javascript and markup options to invisible_recaptcha_tags ONLY we are not in a testing mode
=> Fix invisible_recaptcha_tags to work in testing modes

lib/recaptcha/client_helper.rb, test/client_helper_test.rb
otherwise the url becomes insane with many '?hl=<locale>' params
=> Bug fix: :hl option should not alter api_server_url value

lib/recaptcha/verify.rb
breaks code of ppl that implemented a similar method
@staugaard
=> remove generic remote_ip method

.travis.yml
@wilchandler maybe this works ...
alternative to https://github.com/fakefs/fakefs/pull/383
=> bump ruby versions

README.md, lib/recaptcha/client_helper.rb, test/client_helper_test.rb
=> Support data-error-callback. Document all callbacks

lib/recaptcha/client_helper.rb
https://github.com/ambethia/recaptcha/issues/278
Fixed all errors except `scrolling="no"`.
=> Fix styles of Recaptcha::ClientHelper

README.md, lib/recaptcha/rails.rb
caused by https://github.com/ambethia/recaptcha/pull/268
fixes https://github.com/ambethia/recaptcha/issues/280
@krsyoung @ericproulx
=> add back deprecated file to not blow up copy-pasted gemfile

lib/recaptcha/client_helper.rb
Otherwise the script tag will be blocked by CSP.
=> Default callback also needs nonce, if provided

CHANGELOG.md
=> Update CHANGELOG for latest versions

lib/recaptcha/client_helper.rb, test/client_helper_test.rb
Hello! Just noticed a small error for the :ui => :input option. It now renders correctly with the supplied :text parameter.
=> Corrected value setting for ui input option.

README.md, demo/rails/.env, demo/rails/Readme.md, demo/rails/app/controllers/v3_captchas_controller.rb, demo/rails/app/views/v3_captchas/index.html.erb, demo/rails/config/routes.rb, lib/recaptcha/helpers.rb
=> Fix example of v2 fallback

README.md
alternative for https://github.com/ambethia/recaptcha/pull/327 and removing blah blah that I don't understand 🤷‍♂
=> simplify / improve i18n docs

lib/recaptcha/helpers.rb, test/client_helper_test.rb
Fixes: https://github.com/ambethia/recaptcha/issues/323
=> Remove dependency for rails methods in v3

README.md, lib/recaptcha/helpers.rb, test/client_helper_test.rb
https://github.com/ambethia/recaptcha/issues/342
as I used a monkey patch for that which works for us I'm not sure if it would work for others / doesn't destroy anything.
I'm happy for feedback and I don't think this solution is the best but it works
=> Turbolinks and recaptcha

README.md
Took me a bit to realize I needed two separate keys to do v3 -> v2 callback. Adding in site and secret_key to example to clarify that concept.
=> Clarify that if using v3 -> v2 fallback example

README.md
Also, adding a small note about which version is used in the rails setup example.
=> Adding a table of contents in README 

rails/locales/fr.yml
=> Add french locale

rails/locales/fr.yml
There was a typo in #381 , thanks to @ylecuyer for pointing it out :see_no_evil:
=> Fix typo in french locale file

CHANGELOG.md, README.md, lib/recaptcha.rb, lib/recaptcha/configuration.rb, lib/recaptcha/helpers.rb, test/configuration_test.rb, test/helper.rb, test/verify_enterprise_test.rb, test/verify_test.rb
=> Add support for recaptcha's enterprise API

CHANGELOG.md
Update the changelog to include the latest release.
=> Add 5.10.1 to changelog

CHANGELOG.md, rails/locales/nl.yml
This adds the Dutch translations for the error messages. That's it!
This is a locale we support in our application. Done with Google Translate help - not speaking Dutch myself.
Best regards
=> Add Dutch translations

CHANGELOG.md, rails/locales/ja.yml
This adds the Japanese translations for the error messages 🧡 
Best regards
=> Add Japanese translations

CHANGELOG.md, rails/locales/ja.yml
Fix Japanese locale. It is overriding the English locale.
https://github.com/ambethia/recaptcha/pull/418#discussion_r958234202
=> Fix japanese locale

Gemfile.lock, recaptcha.gemspec
This solves problems which have been described in the [tracking issue](https://github.com/ambethia/recaptcha/issues/427).
Closes https://github.com/ambethia/recaptcha/issues/427.
=> Remove explicit json gem dependency

README.md
See: https://cloud.google.com/recaptcha-enterprise/docs/actions
=> Improve documentation for action names per official documentation

.github/workflows/ci.yml
=> Run rubocop on a supported version of ruby

CHANGELOG.md
@grosser thank you for getting #472 merged!
However I noticed that the changelog entry doesn't match the tag, so just dropping a quick fix to get that sorted.
- [&#x2611;] CHANGELOG.md updated with short summary for user facing changes
=> Fix changelog tag
