lib/recaptcha/client_helper.rb
Support languages for the v2 API (the language param (hl) needs to be passed as a parameter when calling the JS API file).
Usage: `recaptcha_tags hl: 'fr'` (note: works only for the v2 API, e.g. `config.api_version = 'v2'`).
=> Support for language code param for the v2 API

lib/recaptcha/client_helper.rb
With reference to https://github.com/ambethia/recaptcha/issues/130 this
change generates a secure_token based on a random uuid and the integer
time in milliseconds as a JSON message. This is encrypted using the
‘private_key’ and sent to google as a data attribute.
=> Generate stoken and attach it as a data attribute

lib/recaptcha/verify.rb
RAILS_ENV is not always set in development mode, so it would be convenient to rely on Rails.env instead.
=> Switch to Rails.env in env_options

README.md, lib/recaptcha/verify.rb
In cases when `recaptcha_tags` are not used, or at least not directly, it would bi nice to have option to set the response manually.
=> Support for specifying custom response param

lib/recaptcha/verify.rb, test/verify_test.rb
Error messages mentioning "Word verification" are no longer relevant with v2.0 so I suggest to replace them with more generic ones.
=> Update error messages for reCAPTCHA v2.0

lib/recaptcha.rb, test/configuration_test.rb
If an exception is raised inside a `with_configuration` block, then the inner configuration "leaks" outside the block. This PR ensures that the cleanup always takes place.
=> Clean up after with_configuration exception

lib/recaptcha/client_helper.rb
After a recent upgrade I was getting `SSL is always true` all over my Rails 5 feature specs but had no idea what was causing it and how to fix it. I think this clearer error message gives users an action to take to fix it.
=> Provides clearer message with action for recaptcha_tags

lib/recaptcha.rb, lib/recaptcha/configuration.rb
Currently there is an error ```can't modify frozen Array``` when you try to delete ```test``` from ```SKIP_VERIFY_ENV``` array( ```Recaptcha.configuration.skip_verify_env.delete('test')``` ) while testing.
=> Unfreeze SKIP_VERIFY_ENV array

lib/recaptcha/client_helper.rb
reCaptcha [documentation](https://developers.google.com/recaptcha/docs/faq#does-recaptcha-support-users-that-dont-have-javascript-enabled) provides a different fallback HTML version for the `<noscript>` tag, it was probably updated recently and it is causing the fallback iframe to not render properly.
=> Update fallback HTML

README.md, demo/rails/app/views/captcha/index.html.erb, demo/sinatra/server.rb, lib/recaptcha/client_helper.rb, lib/recaptcha/configuration.rb, lib/recaptcha/verify.rb, test/client_helper_test.rb, test/configuration_test.rb, test/helper.rb, test/verify_test.rb
The Recaptcha v2 API uses the names site_key / secret_key instead of public_key
/ private_key. Make the code reflect this change.
=> Rename api keys to v2 scheme

README.md
The PR came while trying to select a different theme for reCaptcha newest version (v2.0).
The reported problem was found while searching through [`client_helper.rb`](https://github.com/ambethia/recaptcha/blob/master/lib/recaptcha/client_helper.rb#L19-L22) and after trying to set the theme like this:
```erb
<%= recaptcha_tags default: { theme: 'blackglass' } %>
```
To make it work I had set theme as below and using [Google's reference for display](https://developers.google.com/recaptcha/docs/display):
```erb
<%= recaptcha_tags theme: 'dark' %>
```
=> [DONE] Show theme option instead of display on readme

demo/rails/.env, demo/rails/app/views/captcha/index.html.erb, lib/recaptcha/client_helper.rb, test/client_helper_test.rb
This pull request adds preliminary support for the [invisible reCAPTCHA](https://developers.google.com/recaptcha/docs/invisible).
It introduces the `invisible_recaptcha_tags` helper, which adds reCAPTCHA's JavaScript resource as well as a submit button. The user also needs to set a callback to handle competition of the captcha using the `callback` option.
More info: https://developers.google.com/recaptcha/docs/invisible#auto_render
=> Add invisible reCAPTCHA support

README.md
This adds usage example for `invisible_recaptcha_tags` to the readme.
`invisible_recaptcha_tags` was originally implemented in #211 by
@juampi and released in 4.1.0.
I found #211 to be useful for what I needed, so I decided to document a
usage example to help others. Please let me know if anything needs to
be corrected.
=> Document `invisible_recaptcha_tags`

lib/recaptcha/configuration.rb, test/configuration_test.rb
This is so that the URL can be set to some proxies instead of the
hardcoded Google links.
This commit is inspired by https://github.com/ambethia/recaptcha/issues/214\#issuecomment-285257412
=> Make api_server_url and verify_url configurable

README.md
current example renders a tiny empty button with no text
=> add button text to invisible_recaptcha_tags example

Gemfile.lock
1.8.3 does not work with ruby 2.4+
=> Update json in Gemfile.lock for ruby 2.4+

lib/recaptcha/verify.rb, test/verify_test.rb
The `remoteip` to verify captcha is optional as per https://developers.google.com/recaptcha/docs/verify. 
Adding an option to skip the remoteip when necessary
=> Skip optional remote ip when posting

README.md, demo/rails/app/views/captcha/index.html.erb, lib/recaptcha/client_helper.rb, test/client_helper_test.rb
~This is a work in progress commit and looking for some ideas.
It is working towards the first part of #220.~
~This adds a default callback that calls the function
`invisibleRecaptchaSubmit` if no callback was passed to
`invisible_recaptcha_tags`~
~The drawback to this approach is that it won't work if there are
multiple recaptcha forms.~
Add default callback for invisible recaptcha #220
This adds a default callback that calls the function
`invisibleRecaptchaSubmit` if no callback was passed to
`invisible_recaptcha_tags`. The function, `invisibleRecaptchaSubmit`,
uses the `closest()` method to find the closest form to the
`.g-recaptcha` element. However, not all browsers support `closest()`,
so in that case, a polyfill of `closest` is executed. The polyfill is
based on MDN's polyfill …
=> Add default callback for invisible recaptcha #220

README.md
If user is working on localost:3000 then localhost will work as a valid domain because localhost:3000 as a domain violates the valid scheme
closes https://github.com/ambethia/recaptcha/issues/241
=> Update readme to create site key for localhost:3000

lib/recaptcha/client_helper.rb, test/client_helper_test.rb
This PR pulls out the `tabindex` data attribute, as documented here https://developers.google.com/recaptcha/docs/display
=> Include `data-tabindex` attribute

README.md
Markdown recognized `and` and as a ruby key word, when that was not the intention.
=> Fix small issue with markdown in readme

lib/recaptcha/client_helper.rb
Currently, a site key is required even for environments where verification is skipped. It is inconvenient to have to define one when it serves no actual purpose.
This PR removes that requirement.
=> Ignore site key for skipped environments

lib/recaptcha/client_helper.rb
Screen reader testers log an error on the Recaptcha iframe because it doesn't have a title
=> added title attribute to iframe for screen readers

lib/recaptcha/client_helper.rb, test/client_helper_test.rb
Calling `recaptcha_tags` (or `invisible_recaptcha_tags`) with the `expired_callback` argument generated a `data-expired_callback` attribute that does not achieve anything. This fixes that behaviour.
Essentially adds tests for #227.
=> Dasherise the `data-expired-callback` attribute name properly.

lib/recaptcha/client_helper.rb, test/client_helper_test.rb
Fixes #255 
In addition to the specific issue with `callback` called out in #255, all kinds of ruby options could leak out into the HTML. For example, if the `env: 'test'` option was provided, the HTML would include `env="test"`. This commit ensures that `recaptcha_components` always consumes all its options so they won't leak into the HTML. 
It would likely be better design to pass desired HTML attributes in a separate Hash instead of interleaving them with ruby options, but that is beyond the scope of this commit. 
I sought to keep behavior as similar as possible, specifically: 
* `data-*` recaptcha-related attributes are not emitted in skipped environments (before they were emitted incorrectly, without the `data-` prefix)
* `class="g-recaptcha"` is emitted even in skipped environments
=> Prevent leaking recaptcha client_helper options as HTML attributes

README.md, lib/recaptcha/client_helper.rb, test/client_helper_test.rb
This PR adds a nonce attribute to script tag, which can be set by passing a `nonce` option.
This is necessary for setting CSP (Content-Security-Policy) header.
See: https://developers.google.com/recaptcha/docs/faq#im-using-content-security-policy-csp-on-my-website-how-can-i-configure-it-to-work-with-recaptcha
=> Allow setting nonce attribute for reCAPTCHA API script

lib/recaptcha/verify.rb
When testing with Capybara it's possible to have the RAILS_ENV environment variable == 'test' and RACK_ENV not set.  In this case Puma (if used as the server) can default RACK_ENV to 'development'.  Since this gem currently prefers RACK_ENV over RAILS_ENV it leads to thinking it is in development mode when it is actually in test mode.  This PR swaps over to preferring RAILS_ENV over RACK_ENV which probably makes sense since when using Rails RAILS_ENV will more accurately reflect the current mode.
=> Prefer ENV['RAILS_ENV'] over ENV['RACK_ENV'] when determining current environment

lib/recaptcha/client_helper.rb, test/client_helper_test.rb
As `invisible_recaptcha_tags` generates a `<button>`, it should have a normal `tabindex` attribute, rather than a `data-tabindex` attribute to be picked up by the Recaptcha JS.
=> Leave tabindex attribute alone for invisible_recaptcha_tags

.rubocop.yml, Gemfile.lock, lib/recaptcha/client_helper.rb, lib/recaptcha/rails.rb
For some reason, Rubocop misconfigured file list with only `Rakefile` & `Gemfile`, so I changed that to fix Rubocop linting and fixed the issues.
=> Make rubocop work again

README.md, lib/recaptcha/client_helper.rb, test/client_helper_test.rb
This allows you pass the `onload` and `render` options which are useful for explicit rendering. More detail on these options in [the docs](https://developers.google.com/recaptcha/docs/display#explicit_render).
=> Add onload and render

lib/recaptcha/client_helper.rb
The scrolling attribute on the iframe element is obsolete. Use CSS instead
=> remove deprecated scrolling attribute for iframe

lib/recaptcha/verify.rb, test/verify_test.rb
Submitting a verify request with a long (~4000) `g-recaptcha-response` will cause the endpoint to return a 400 error instead of a 200 response with a json body. For even larger payloads, this will return a 413 error.
This causes an error in the reply parsing since we're expecting a json response. https://github.com/ambethia/recaptcha/blob/master/lib/recaptcha/verify.rb#L79
Verifying this from https://www.google.com/recaptcha/api2/demo, the actual g-recaptcha-response should only be ~335 characters long. 
Make a request with 4095 characters in the `response` parameter. Note doing this this in browsers may truncate the request. 
```
https://www.google.com/recaptcha/api/siteverify?secret=YOURSECRETHERE&response=unexisting/../../../../../../../../../../windows/win.ini.\.\.\.\.\.\.\.\.\.\.\.\.\ …
```
=> Fail fast for long g-responses

lib/recaptcha/configuration.rb, test/configuration_test.rb, test/verify_test.rb
Apologies for the duplicate PR, I was feeling impatient (See #306). For reference, the google documentation [can be found here](https://developers.google.com/recaptcha/docs/faq#can-i-use-recaptcha-globally):
=> Recaptcha.net for international users

lib/recaptcha/railtie.rb, rails/locales/en.yml, recaptcha.gemspec
Closes #326.
Adds `rails/locales` directory and reads translations it. `en.yml` included, more can be added later!
=> Allow addition of more translations

lib/recaptcha.rb
With the current implementation the default timeout is never used because a `timeout` argument is always passed to `api_verification`. This was made obvious today when reCAPTCHA was having issues and we saw network request times as long as 2 minutes.
=> Use default if timeout is nil

lib/recaptcha/helpers.rb, test/client_helper_test.rb
For `recaptcha_v3` helper there was extra closing script tag.
```html
<script src="https://www.recaptcha.net/recaptcha/api.js?render=0000000000000000000000000000000000000000"   ></script>
<script>
// Define function so that we can call it again later if we need to reset it
// This executes reCAPTCHA and then calls our callback.
function executeRecaptchaForFoo() {
grecaptcha.ready(function() {
grecaptcha.execute('0000000000000000000000000000000000000000', {action: 'foo'}).then(function(token) {
//console.log('g-recaptcha-response-foo', token)
setInputWithRecaptchaResponseTokenForFoo('g-recaptcha-response-foo', token)
});
});
};
// Invoke immediately
executeRecaptchaForFoo()
// Async variant so you can await this function from another async function (no need for
// an explicit callback …
```
=> V3 remove obsolete script tag

README.md, lib/recaptcha/adapters/controller_methods.rb, lib/recaptcha/helpers.rb, test/client_helper_test.rb, test/verify_test.rb
Recently for recaptcha_v3 helper recaptcha script starts generating new empty textarea with the same name `g-recaptcha-response` as what is used for checking resulting response token. As a result recaptcha is trying to check empty field and failed. For fix and prevent this problem in a future (we don't know what google will change next), i added to the attribute name unique token based on `site_key`.
More info #353
=> added 'data' postfix to g-recaptcha-response attribute name

lib/recaptcha/adapters/controller_methods.rb
For support v2 and v3 we need to check `g-recaptcha-response-data` and  `g-recaptcha-response` parameters
=> fix verify_recaptcha for v2

README.md, lib/recaptcha.rb, lib/recaptcha/adapters/controller_methods.rb, test/verify_test.rb
As mentioned in #343
It would be very helpful to be able to get the recaptcha v3 score, for logging purposes for example, or to have different responses given the score (more than just a binary yes/no)
This PR is WIP, I just want to validate the implementation, as I'm adding some public methods and tweaking a bit the `verify_via_api_call` by returning a tuple which is a bit weird.
If you are ok with the implem, I will add tests and update the doc.
Otherwise, if you have suggestions I'm all ears
Thanks
=> Expose recaptcha reply (and score) to the controller

demo/rails/app/views/v3_captchas/index.html.erb
-Async function version is being generated only when inline_script is true.
-Fix element id
ID generated are structured like "g-recaptcha-response-data-#{action}"
=> Fix execute on submit demo example

lib/recaptcha/helpers.rb, test/client_helper_test.rb
I ran into an issue where I had two forms with `invisible_recaptcha_tags` on a single page. The main form is a contact-us form, while a second newsletter-subscribe form is always present in the footer.
When submitting either form, it would then always submit the form for the _first_ button (`var form = closestForm(eles[0]);`) it could find.
This PR is an attempt to add functionality for passing an optional `selector` prop which lets you have multiple recaptcha-protected forms on a single page, as long as you uniquely name your selector props.
Curious to what you think of this. I realise it's a bit of an edge-case.
=> Allow multiple invisible recaptchas on a single page by setting custom selector

CHANGELOG.md, lib/recaptcha/adapters/controller_methods.rb, test/verify_test.rb
Fixes: #387
This gracefully handles a situation in which requests are made without a valid `g-recaptcha-response-data` or `g-recaptcha-response` parameter, usually these requests come from automated scripts or bots, but it is preferable to not raise an exception (`TypeError: no implicit conversion from nil to integer`) in this case.
=> Handle invalid params in ControllerMethods#recaptcha_response_token

.github/workflows/ci.yml
I want to ensure this gem works on new Rubies (e.g. 3.0).
~~This change also includes:~~
- ~~removing `Gemfile.lock` for a more flexible dependency installation~~
- ~~renaming the old RuboCop cop names~~
My fork is working: https://github.com/ybiquitous/recaptcha/pull/1
=> Add new Rubies to CI matrix

README.md, lib/recaptcha.rb, test/verify_enterprise_test.rb, test/verify_test.rb
This gem can be used with hCaptcha, but hCaptcha scores are inverse to reCaptcha scores.
hCaptchascores: 0.0 (no risk) to 1.0 (high risk)
reCaptcha scores scores: 0.0 (high risk) to 1.0 (no risk)
This change is meant to add a `maximum_score` attribute that can be called with `verify_recaptcha`.
It works just like `minimum_score`, but allows for the same idea to work when using hCaptcha.
=> Add maixmum score for use with hCaptcha

lib/recaptcha/configuration.rb, test/verify_enterprise_test.rb
`enterprise_verify_url` were out of date.
So I updated enterprise_verify_url version from v1beta1 to v1.
- References
- [reCAPTCHA Enterprise API](https://cloud.google.com/recaptcha-enterprise/docs/reference/rest)
- [v1beta1 Method: projects.assessments.create](https://cloud.google.com/recaptcha-enterprise/docs/reference/rest/v1beta1/projects.assessments/create)
- [v1 Method: projects.assessments.create](https://cloud.google.com/recaptcha-enterprise/docs/reference/rest/v1/projects.assessments/create)
=> Fix enterprise_verify_url

CHANGELOG.md, lib/recaptcha.rb
Setting the minimum_score attribute to anything would cause the v3 check to fail automatically when using reCAPTCHA Enterprise because the score accessor was incorrect and would return nil every time. I simply corrected the accessor for the score attribute coming back from the API and it works again.
=> Fix minimum_score for enterprise API

CHANGELOG.md, lib/recaptcha.rb, test/verify_enterprise_test.rb
Hey sorry, I decided to go back and check the reCAPTCHA Enterprise API documentation, and it turns out that the old accessor was correct for the v1beta API, but now on the official v1 api it uses the new accessor exclusively:
https://cloud.google.com/recaptcha-enterprise/docs/reference/rest/v1beta1/projects.assessments
https://cloud.google.com/recaptcha-enterprise/docs/reference/rest/v1/projects.assessments#ClassificationReason
So I updated the enterprise tests and removed the fallback for the old accessor.
=> Remove enterprise score fallback and modify enterprise tests to v1 assessments 

CHANGELOG.md, README.md, lib/recaptcha/helpers.rb, test/client_helper_test.rb
This pull request adds an option to the recaptcha_v3 view helper called ignore_no_element. This option is added to avoid a common issue in which the element of the callback function is null after a modal is closed, causing the function to throw an error. This option is not required, and if it is not set, the view helper will continue to work as usual. This pull request was made to resolve the issue requests in the repo recaptcha. 
Fixes #424 
Let me know if there anything else you would like me to add.
- added test cases
- changelog message
- readme documentation
- backwards compatible changes to recaptcha_v3
-  all passing tests
=> Add option to ignore null elements in recaptcha_v3 view helper.

lib/recaptcha.rb, test/verify_enterprise_test.rb
This commit allows the user to pass in the expected action as a symbol.
Previously we would compare the string action with the symbol action and we'd think the action was invalid because `'homepage' != :homepage`.
Thanks! 😄 
_(I may need some guidance on updating the CHANGELOG—does this require a version change? )_
=> Permit actions as symbol

.github/workflows/ci.yml, CHANGELOG.md
Add 3.2 to the list of Ruby CI versions
=> Add 3.2 to the list of Ruby CI versions

CHANGELOG.md, README.md, lib/recaptcha.rb
Certain reCAPTCHA-compatible services require that the server verification be submitted via POST rather than GET.
An example is Cloudflare Turnstile:
https://developers.cloudflare.com/turnstile/migration/migrating-from-recaptcha/#server-side-integration
That documentation calls out the requirement for the verification call be done via POST.
This PR adds the ability to supply options[:json] = true (defaults to false) to submit the data as POST with JSON body.
=> Add HTTP POST support with JSON body for server-side verification (`verify_recaptcha`)

CHANGELOG.md, README.md, lib/recaptcha/helpers.rb, test/client_helper_test.rb
=> Allow the use of `turbo` to enable turbo functionality for `recaptcha_v3`

CHANGELOG.md, README.md
I found it a bit confusing to understand how the keys worked when initially going through the examples. The v3 keys were set per call, while the v2 keys were set using environment variables.
I've updated the example to indicate where the v2 keys come from.
=> Add key setup to v3 example in README

CHANGELOG.md, lib/recaptcha/helpers.rb
This was unused and may cause accessibility concerns if there is more than one recaptcha on the page due to multiple elements with the same id
Fixes #439
=> Remove unnecessary id on textarea

.github/workflows/ci.yml, .rubocop.yml, CHANGELOG.md, recaptcha.gemspec
Ruby 2.7 is past EOL, so we're no longer supporting it.
=> Drop support for ruby 2.7, add 3.3

.github/PULL_REQUEST_TEMPLATE.md, Gemfile.lock
This prevents the deprecation warning:
> Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
=> Update to the latest version of bundler

CHANGELOG.md, rails/locales/de.yml, rails/locales/es.yml, rails/locales/it.yml, rails/locales/pt-BR.yml, rails/locales/pt.yml
Just adding a few more languages to the i18n support:
- German
- Spanish
- Italian
- Portuguese
- Portuguese (Brazil)
It's handy to have a wide range of languages supported out-of-the-box so users of the gem don't need to add their own translations every time.
=> Add i18n: de, es, it, pt, pt-BR

README.md
Add `content_security_policy` as suggestion to set `nonce` in a Rails context. 
Example:
```
<%= recaptcha_tags(nonce: content_security_policy_nonce) %>
```
=> Suggest content_security_policy in doc

lib/recaptcha/helpers.rb, test/client_helper_test.rb
The 'inline_script' option is leaking out as an attribute for the input element. This is getting flagged by some a11y tools. For example, from https://validator.w3.org/nu:
`Error: Attribute inline_script not allowed on element [input](https://html.spec.whatwg.org/multipage/#the-input-element) at this point.`
I don't think it is necessary in the markup, but alternatively we could move it to a data attribute if there's a need I'm not seeing.
=> Remove inline_script attribute from markup

CHANGELOG.md, README.md, lib/recaptcha/adapters/controller_methods.rb, test/verify_test.rb
This update introduces the `recaptcha_failure_reason` method to provide developers with detailed information on common verification failures. This enhancement aims to improve debugging and error handling when integrating to applications.
I had annoying moments debugging errors when using the gem. Gem itself worked nicely but the error messages needed some manual work. E.g. when custom javascripts set the request parameter correctly but with wrong name, the gem didn't give any errors it just failed. I wanted to have simpler error messages. This also helps when logging the results as now I have single method to return some information.
**Key Changes:**
- Added `recaptcha_failure_reason` method in `controller_methods.rb` to return detailed failure reasons.
- Updated `verify_recaptcha` method …
=> Add recaptcha_failure_reason for enchanced error reporting

README.md, lib/recaptcha.rb, lib/recaptcha/configuration.rb, test/verify_enterprise_test.rb, test/verify_test.rb
Add minimum length validation for the recaptcha token param
Reason:
https://github.com/ambethia/recaptcha/issues/461
Spammers can pass random value for the token param (ex: g-recaptcha-response) which can increase the API validation call to recaptcha, consequently incurring more cost.
Most of the Spam attacks we observed attacher sending 1-10 length chars.
It is good to have minimum length 100, validation check to avoid unnecessary API calls to recaptcha.
=> Minimum length validation for the recaptcha token param

lib/recaptcha.rb
PR to fix #470.
According to #470, when verifying the `reCAPTCHA` token with `verify_recaptcha`, the HTTP request sent to Google's endpoint does not include a **Referer** header. Google rejects the request with a **403 Permission Denied** error because the request lacks the expected referer/origin information.
This PR adds a **Referer** header during `api_verification_enterprise` method with a default value of `Rails.application.default_url_options[:host]`.
Any improvement is welcome !
=> add referer header to #api_verification_entreprise
